### ISSUE TITLE
Add README 

### ISSUE THREAD

**Issue by Evavic44** [EkeHub/signup-form#1]
Add a simple readme with information about this community. 
Use this example as an inspiration: 
https://github.com/Evavic44/Hotel-Zeitaku/blob/main/README.md

What I want to see basically is:
- [x] Name of this project
- [x] A screenshot of the form
- [x] What this particular form is for and about.
- [x] #6
`Username: Add your github username here.`

**Comment by Mannuel25** [comment]
Hey Eke, I'd like to take up this issue 😅

**Comment by Evavic44** [comment]
Go ahead man. Also if you'll love to be a part of this community, fill this form. 🥳 https://ekehub-signup.netlify.app/

**Comment by Evavic44** [comment]
@Mannuel25 , I made some changes to the form. 
Can you kindly fill it again? 🙃
