### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Evavic44** [EkeHub/signup-form#2]
Add the community favicon.

## Image
![ekehub](https://user-images.githubusercontent.com/62628408/136641252-8a704f3a-d039-41cd-a766-7e19b896398d.png)
 
## Resource 
https://favicon.io/favicon-converter/

**Comment by Evavic44** [comment]
Since @kamalrt11 signified first, I'll let him handle this issue.@akshaygidwani404  you can work on issue #1 if you like. 😎

**Comment by kamalrt11** [comment]
<img width="711" alt="q" src="https://user-images.githubusercontent.com/54072216/136658309-ca35a7bf-502f-458f-8396-1eaddc065aca.png">

Why it is showing the Project is Not Participating? Can you please look into this matter?
